### ISSUE TITLE
sqlite db missing table schema 

### ISSUE THREAD

**Issue by digen** [fosstr/rsvp#11]
Upon starting the Django server and accessing http://127.0.0.1:8000/rsvp/events/, 

`(rsvp)maverick:fosstr_rsvp swapneel$ tail -f rsvp.log
    cursor.execute(sql, params)
  File "/Users/swapneel/dev/python/rsvp/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/swapneel/dev/python/rsvp/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/swapneel/dev/python/rsvp/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/swapneel/dev/python/rsvp/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 485, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such column: fosstr_rsvp_event.maximum_attendees`

**Comment by hiteshd** [comment]
This is not a issue per say. Since the sqlite DB commited to this is a barebones db. You will have to locally run `python manage.py syncdb`.

Additionally you can use `south` for managing db changes and migrations

**Comment by hrj** [comment]
Will running `python manage.py syncdb` cause a migration to be run?

In that case, can it be run automatically upon server start?

**Comment by hiteshd** [comment]
The problem here is the following.

A SQLite DB schema was formed after looking at the event model. The event model was then changed to include an additional field for 'maximum_attendes'. This change is not reflected in the DB on git yet. 

It is my mistake to commit the DB to the git repo. When an app is deployed, It is a one time step to run syncdb before you start and stop the app.

For clarity. I am committing a functional DB to the repo now and closing this
